language: perl
perl:
  - "5.16"
  - "5.14"
before_install:
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: yes | (perl Build.PL && ./Build && cover -test)
after_success:
  - cover -report coveralls
notifications:
  email:
    - hirose31+travis@gmail.com

